# -*- coding: utf-8 -*-
"""sistema_de_auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-A9ARWN4M7nPuxSoHwXMXI3zqEfTouj

Sistema de auditoria de recursos corporativos


* Yasmin De Matos Reis
"""

def calcular_orcamento():